FROM projectserum/build:v0.27.0

# RUN apt update && apt install -y wget unzip git

# WORKDIR /root
# RUN wget https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v1.0.8/aptos-cli-1.0.8-Ubuntu-22.04-x86_64.zip
# RUN unzip aptos-cli-1.0.8-Ubuntu-22.04-x86_64.zip -d /usr/local/bin

WORKDIR /local